apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ghost
  labels:
    app: test-ghost
spec:
  replicas: 5
  revisionHistoryLimit: 25
  selector:
    matchLabels:
      app: test-ghost
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-ghost
    spec:
      containers:
      - name: test-ghost
        image: jetalone/test-ghost:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 50Mi